#!/usr/bin/env python3
"""
Stage 2: LightGBM Screener Training, Validation, and Active Negative Mining.

1. Extracts dense features for candidate pairs generated by Blocking.
2. Trains LightGBM binary classifier on training pairs.
3. Evaluates macro F_0.5 on held-out validation set and sweeps decision thresholds.
4. Mines active hard negatives (LightGBM false positives) for Stage 3 TensorFlow specialist training.
"""

import argparse
import csv
import json
import os
import pickle
import time
from typing import Dict, List, Tuple

import lightgbm as lgb
import numpy as np

from .config import (
    TRAIN_SOURCE1_PATH,
    TRAIN_SOURCE2_PATH,
    TRAIN_SOURCE3_PATH,
    TRAIN_GROUND_TRUTH_PATH,
    MINI_VAL_GROUND_TRUTH_PATH,
    MINI_VAL_S1_IDS_PATH,
    MODELS_DIR,
    SPLIT_DIR,
    LGBM_PARAMS,
    MAX_CANDIDATES_PER_S1,
    TRAIN_CANDIDATE_INDEX_DUCKDB_PATH,
    THRESHOLD_AUTO_ACCEPT,
    THRESHOLD_AUTO_REJECT,
)
from .blocking import read_entity_csv
from .duckdb_blocking import DuckDBBlockingEngine
from .features import extract_pair_features, add_group_relative_features, FEATURE_NAMES
from .evaluate import evaluate_predictions, load_mapping_file
from .normalize import normalize_business_name, normalize_address

# Chunk size for batched candidate retrieval - matches pipeline_duckdb.py's
# default, so training sees the same retrieval behavior real inference does.
RETRIEVAL_CHUNK_SIZE = 4000


def build_pair_dataset(
    s1_records: List[Dict[str, str]],
    engine: DuckDBBlockingEngine,
    ground_truth_map: Dict[str, set],
    max_neg_ratio: int = 4,
    include_missed_positives: bool = True,
) -> Tuple[np.ndarray, np.ndarray, List[Dict[str, str]], Dict[str, List[str]]]:
    """
    Retrieve REAL blocking candidates from the full-scale DuckDB index for
    each S1 record (mirroring exactly what pipeline_duckdb.py does at test
    time, including transliteration - since DuckDBBlockingEngine.build_index()
    applies it), extract features/labels for those pairs. Retrieval is
    batched (RETRIEVAL_CHUNK_SIZE at a time via retrieve_candidates_batch())
    rather than one entity per call, the same batching pipeline_duckdb.py
    uses for test-time inference.

    include_missed_positives=True additionally injects true-match candidates
    that blocking missed (looked up directly by id) as extra positive training
    signal. This is useful for TRAINING but must be False for VALIDATION,
    since the real pipeline can never predict a match that its own blocking
    stage didn't retrieve - including missed positives in eval would
    overstate achievable recall/precision relative to the real deployed
    pipeline.
    """
    X_rows = []
    y_labels = []
    meta = []
    blocking_results = {}

    for chunk_start in range(0, len(s1_records), RETRIEVAL_CHUNK_SIZE):
        chunk = s1_records[chunk_start:chunk_start + RETRIEVAL_CHUNK_SIZE]

        # {s1_id: [(cid, name, addr, norm_name, norm_addr), ...]} for the
        # whole chunk in one batched JOIN. norm_name/norm_addr are
        # already-computed at index-build time, so extract_pair_features()
        # below doesn't need to re-normalize the candidate side from raw text.
        retrieved_by_s1 = engine.retrieve_candidates_batch(chunk)

        for s1 in chunk:
            s1_id = s1["entity_id"]
            true_cids = ground_truth_map.get(s1_id, set())

            retrieved = retrieved_by_s1.get(s1_id, [])
            cand_lookup = {
                cid: (name, addr, norm_name, norm_addr)
                for cid, name, addr, norm_name, norm_addr in retrieved
            }
            blocking_results[s1_id] = list(cand_lookup.keys())

            if include_missed_positives:
                # Ensure true matches missed by blocking are still available
                # as positive training examples (looked up directly by id).
                for cid in true_cids:
                    if cid not in cand_lookup:
                        row = engine.get_by_id(cid)
                        if row is not None:
                            name, addr, _country, norm_name, norm_addr = row
                            cand_lookup[cid] = (name, addr, norm_name, norm_addr)

            # Normalize this S1's own name/address once, reused for every one
            # of its candidate pairs below instead of re-normalizing per pair.
            s1_norm_name = normalize_business_name(s1["business_name"])
            s1_norm_addr = normalize_address(s1["business_address"])

            # Extract features for the FULL retrieved group first (relative
            # features below need every candidate, not just the ones
            # negative-subsampling below will keep - see
            # add_group_relative_features()'s docstring).
            group = []
            for cid, (cand_name, cand_addr, cand_norm_name, cand_norm_addr) in cand_lookup.items():
                is_match = 1 if cid in true_cids else 0
                feats = extract_pair_features(
                    s1["business_name"],
                    s1["business_address"],
                    cand_name,
                    cand_addr,
                    cid,
                    s1_norm_name=s1_norm_name,
                    s1_norm_addr=s1_norm_addr,
                    cand_norm_name=cand_norm_name,
                    cand_norm_addr=cand_norm_addr,
                )
                group.append((cid, feats, is_match))

            add_group_relative_features([f for _, f, _ in group])

            neg_count = 0
            for cid, feats, is_match in group:
                if not is_match:
                    neg_count += 1
                    if max_neg_ratio and neg_count > max(len(true_cids) * max_neg_ratio, 10):
                        continue
                X_rows.append([feats[k] for k in FEATURE_NAMES])
                y_labels.append(is_match)
                meta.append({"s1_id": s1_id, "cand_id": cid})

    X = np.array(X_rows, dtype=np.float32)
    y = np.array(y_labels, dtype=np.int32)
    return X, y, meta, blocking_results


def train_screener(
    train_sample_size: int = 80000,
    val_sample_size: int = 8000,
    lgbm_params: dict = None,
):
    print("=" * 60)
    print("  STAGE 2: TRAINING LIGHTGBM SCREENER & HARD NEGATIVE MINER")
    print("=" * 60)

    val_ids = set()
    with open(MINI_VAL_S1_IDS_PATH, "r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            if idx < val_sample_size:
                val_ids.add(line.strip())

    train_ids = set()
    with open(TRAIN_GROUND_TRUTH_PATH, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.reader(f)
        header = next(reader)
        s1_col = 1 if len(header) > 2 and header[1] == "source1_entity_id" else 0
        if "source1_entity_id" in header:
            s1_col = header.index("source1_entity_id")

        for row in reader:
            if not row or len(row) <= s1_col:
                continue
            sid = row[s1_col].strip()
            if sid not in val_ids:
                train_ids.add(sid)
                if len(train_ids) >= train_sample_size:
                    break

    print(f"Loaded {len(train_ids)} train S1 IDs and {len(val_ids)} val S1 IDs.")

    train_gt = load_mapping_file(TRAIN_GROUND_TRUTH_PATH)
    val_gt = load_mapping_file(MINI_VAL_GROUND_TRUTH_PATH)

    t0 = time.time()
    all_s1_records = read_entity_csv(TRAIN_SOURCE1_PATH, allowed_ids=train_ids | val_ids)
    train_s1_records = [r for r in all_s1_records if r["entity_id"] in train_ids]
    val_s1_records = [r for r in all_s1_records if r["entity_id"] in val_ids]
    print(f"Loaded {len(train_s1_records)} train S1 and {len(val_s1_records)} val S1 records in {time.time()-t0:.2f}s")

    # Build (or reuse) a disk-backed candidate index over the FULL training
    # S2/S3 pool - the same DiskBlockingEngine class and full record scale
    # that pipeline.py searches at test time. This replaces the previous
    # approach of indexing only the first 200,000 rows of each file plus a
    # guaranteed injection of every true-match candidate, which made the
    # negative distribution seen during training/validation both tiny and
    # unrealistically easy relative to what the deployed pipeline faces.
    #
    # DuckDBBlockingEngine, not DiskBlockingEngine (SQLite) - the same engine
    # pipeline_duckdb.py uses at real test time, so training-time candidate
    # retrieval (including transliteration, applied in build_index() below)
    # matches what the deployed pipeline actually does. See
    # documents/engineering_log.md for why this was migrated.
    engine = DuckDBBlockingEngine(db_path=TRAIN_CANDIDATE_INDEX_DUCKDB_PATH, max_candidates=MAX_CANDIDATES_PER_S1)
    if os.path.exists(TRAIN_CANDIDATE_INDEX_DUCKDB_PATH):
        print(f"Using existing full-scale train candidate index: {TRAIN_CANDIDATE_INDEX_DUCKDB_PATH}")
        engine.open(read_only=True)
    else:
        print(f"Building full-scale train candidate index at {TRAIN_CANDIDATE_INDEX_DUCKDB_PATH} "
              f"(indexing all of {os.path.basename(TRAIN_SOURCE2_PATH)} + {os.path.basename(TRAIN_SOURCE3_PATH)})...")
        t0 = time.time()
        engine.build_index(TRAIN_SOURCE2_PATH, TRAIN_SOURCE3_PATH, reset=True)
        print(f"Index built in {time.time()-t0:.1f}s")

    print("Retrieving real full-scale blocking candidates + extracting features for training pairs...")
    t0 = time.time()
    X_train, y_train, train_meta, train_blocking = build_pair_dataset(
        train_s1_records, engine, train_gt, max_neg_ratio=5, include_missed_positives=True,
    )
    print(f"Train dataset: {X_train.shape[0]} pairs (Positives: {np.sum(y_train)}, Negatives: {np.sum(y_train==0)}) in {time.time()-t0:.1f}s")

    print("Retrieving real full-scale blocking candidates + extracting features for validation pairs...")
    t0 = time.time()
    X_val, y_val, val_meta, val_blocking = build_pair_dataset(
        val_s1_records, engine, val_gt, max_neg_ratio=None, include_missed_positives=False,
    )
    print(f"Val dataset:   {X_val.shape[0]} pairs (Positives: {np.sum(y_val)}, Negatives: {np.sum(y_val==0)}) in {time.time()-t0:.1f}s")

    params = lgbm_params if lgbm_params is not None else LGBM_PARAMS
    print(f"Training LightGBM model... (params: {'tuned' if lgbm_params is not None else 'default'})")
    dtrain = lgb.Dataset(X_train, label=y_train, feature_name=FEATURE_NAMES)
    dval = lgb.Dataset(X_val, label=y_val, feature_name=FEATURE_NAMES, reference=dtrain)

    model = lgb.train(
        params,
        dtrain,
        valid_sets=[dtrain, dval],
        callbacks=[lgb.log_evaluation(period=50)],
    )

    print("\n--- Top 10 Most Important Features ---")
    importances = model.feature_importance(importance_type="gain")
    sorted_idx = np.argsort(importances)[::-1]
    for idx in sorted_idx[:10]:
        print(f"  {FEATURE_NAMES[idx]:<25}: {importances[idx]:.1f}")

    model_path = os.path.join(MODELS_DIR, "screener_lgbm.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(model, f)
    print(f"\nModel saved to {model_path}")

    print("\n" + "=" * 50)
    print("      SWEEPING DECISION THRESHOLDS FOR MACRO F_0.5")
    print("=" * 50)
    val_probs = model.predict(X_val)

    best_thresh = 0.50
    best_f05 = 0.0

    for thresh in np.arange(0.40, 0.95, 0.05):
        pred_map = {r["entity_id"]: set() for r in val_s1_records}
        for i, p in enumerate(val_probs):
            if p >= thresh:
                s1_id = val_meta[i]["s1_id"]
                cid = val_meta[i]["cand_id"]
                pred_map[s1_id].add(cid)

        eval_truth = {r["entity_id"]: val_gt.get(r["entity_id"], set()) for r in val_s1_records}
        macro_f05, stats = evaluate_predictions(eval_truth, pred_map)
        print(f"Threshold: {thresh:.2f} | Macro F_0.5: {macro_f05:.4f} | Singleton Acc: {stats['singleton_accuracy']:.2%} | Non-Singleton F0.5: {stats['non_singleton_f05']:.4f}")

        if macro_f05 > best_f05:
            best_f05 = macro_f05
            best_thresh = thresh

    print("=" * 50)
    print(f"BEST THRESHOLD: {best_thresh:.2f} => MACRO F_0.5: {best_f05:.4f}")
    print("=" * 50)

    print("\nMining active hard negatives from training candidate pairs...")
    train_probs = model.predict(X_train)
    hard_negatives = []
    s1_dict = {r["entity_id"]: r for r in train_s1_records}

    for i, p in enumerate(train_probs):
        if y_train[i] == 0 and p >= 0.35:
            s1_id = train_meta[i]["s1_id"]
            cid = train_meta[i]["cand_id"]
            if s1_id in s1_dict:
                s1 = s1_dict[s1_id]
                cand_row = engine.get_by_id(cid)
                if cand_row is None:
                    continue
                cand_name, cand_addr, cand_country, _cand_norm_name, _cand_norm_addr = cand_row
                hard_negatives.append({
                    "s1_id": s1_id,
                    "s1_name": s1["business_name"],
                    "s1_addr": s1["business_address"],
                    "s1_country": s1["country"],
                    "cand_id": cid,
                    "cand_name": cand_name,
                    "cand_addr": cand_addr,
                    "cand_country": cand_country,
                    "lgbm_score": round(float(p), 4),
                    "label": "DIFFERENT",
                })

    hard_neg_path = os.path.join(SPLIT_DIR, "active_hard_negatives.csv")
    with open(hard_neg_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "s1_id", "s1_name", "s1_addr", "s1_country",
            "cand_id", "cand_name", "cand_addr", "cand_country",
            "lgbm_score", "label"
        ])
        writer.writeheader()
        writer.writerows(hard_negatives)

    print(f"Mined {len(hard_negatives)} hard negatives saved to: {hard_neg_path}")
    engine.close()
    print("Stage 2 completed successfully!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-sample-size", type=int, default=80000)
    parser.add_argument("--val-sample-size", type=int, default=8000)
    parser.add_argument("--lgbm-params-json", type=str, default=None,
                         help="Path to tune_screener.py's results JSON (data_split/tune_screener_results.json) "
                              "- uses the top-ranked entry's params instead of config.py's LGBM_PARAMS")
    args = parser.parse_args()

    lgbm_params = None
    if args.lgbm_params_json:
        with open(args.lgbm_params_json) as f:
            results = json.load(f)
        best = results[0] if isinstance(results, list) else results
        lgbm_params = best["params"]
        print(f"Loaded tuned params from {args.lgbm_params_json}: {lgbm_params}")
        print(f"(that trial scored macro_f05={best.get('macro_f05')}, name_sim_floor={best.get('name_sim_floor')} "
              f"- floor is applied at scoring time in decode.py/pipeline_duckdb.py, not here)")

    train_screener(train_sample_size=args.train_sample_size, val_sample_size=args.val_sample_size, lgbm_params=lgbm_params)
