#!/usr/bin/env python3
"""
Stage 2: LightGBM Screener Training, Validation, and Active Negative Mining.

1. Extracts dense features for candidate pairs generated by Blocking.
2. Trains LightGBM binary classifier on training pairs.
3. Evaluates macro F_0.5 on held-out validation set and sweeps decision thresholds.
4. Mines active hard negatives (LightGBM false positives) for Stage 3 LLM specialist training.
"""

import argparse
import csv
import os
import pickle
import time
from typing import Dict, List, Tuple

import lightgbm as lgb
import numpy as np

from .config import (
    TRAIN_SOURCE1_PATH,
    TRAIN_SOURCE2_PATH,
    TRAIN_SOURCE3_PATH,
    TRAIN_GROUND_TRUTH_PATH,
    MINI_VAL_GROUND_TRUTH_PATH,
    MINI_VAL_S1_IDS_PATH,
    MODELS_DIR,
    SPLIT_DIR,
    LGBM_PARAMS,
    THRESHOLD_AUTO_ACCEPT,
    THRESHOLD_AUTO_REJECT,
)
from .blocking import BlockingEngine, read_entity_csv
from .features import extract_pair_features, FEATURE_NAMES
from .evaluate import evaluate_predictions, load_mapping_file


def build_pair_dataset(
    s1_records: List[Dict[str, str]],
    candidates_dict: Dict[str, Dict[str, str]],
    blocking_results: Dict[str, List[str]],
    ground_truth_map: Dict[str, set],
    max_neg_ratio: int = 4,
) -> Tuple[np.ndarray, np.ndarray, List[Dict[str, str]]]:
    """Extract features and labels for candidate pairs."""
    X_rows = []
    y_labels = []
    meta = []

    s1_dict = {r["entity_id"]: r for r in s1_records}

    for s1_id, cand_ids in blocking_results.items():
        if s1_id not in s1_dict:
            continue
        s1 = s1_dict[s1_id]
        true_cids = ground_truth_map.get(s1_id, set())

        all_eval_cids = list(set(cand_ids) | (true_cids & set(candidates_dict.keys())))

        neg_count = 0
        for cid in all_eval_cids:
            if cid not in candidates_dict:
                continue
            cand = candidates_dict[cid]
            is_match = 1 if cid in true_cids else 0

            if not is_match:
                neg_count += 1
                if max_neg_ratio and neg_count > max(len(true_cids) * max_neg_ratio, 10):
                    continue

            feats = extract_pair_features(
                s1["business_name"],
                s1["business_address"],
                cand["business_name"],
                cand["business_address"],
                cid,
            )
            X_rows.append([feats[k] for k in FEATURE_NAMES])
            y_labels.append(is_match)
            meta.append({"s1_id": s1_id, "cand_id": cid})

    X = np.array(X_rows, dtype=np.float32)
    y = np.array(y_labels, dtype=np.int32)
    return X, y, meta


def train_screener(
    train_sample_size: int = 15000,
    val_sample_size: int = 3000,
):
    print("=" * 60)
    print("  STAGE 2: TRAINING LIGHTGBM SCREENER & HARD NEGATIVE MINER")
    print("=" * 60)

    val_ids = set()
    with open(MINI_VAL_S1_IDS_PATH, "r", encoding="utf-8") as f:
        for idx, line in enumerate(f):
            if idx < val_sample_size:
                val_ids.add(line.strip())

    train_ids = set()
    with open(TRAIN_GROUND_TRUTH_PATH, "r", encoding="utf-8", errors="replace") as f:
        reader = csv.reader(f)
        header = next(reader)
        s1_col = 1 if len(header) > 2 and header[1] == "source1_entity_id" else 0
        if "source1_entity_id" in header:
            s1_col = header.index("source1_entity_id")

        for row in reader:
            if not row or len(row) <= s1_col:
                continue
            sid = row[s1_col].strip()
            if sid not in val_ids:
                train_ids.add(sid)
                if len(train_ids) >= train_sample_size:
                    break

    print(f"Loaded {len(train_ids)} train S1 IDs and {len(val_ids)} val S1 IDs.")

    train_gt = load_mapping_file(TRAIN_GROUND_TRUTH_PATH)
    val_gt = load_mapping_file(MINI_VAL_GROUND_TRUTH_PATH)

    t0 = time.time()
    all_s1_records = read_entity_csv(TRAIN_SOURCE1_PATH, allowed_ids=train_ids | val_ids)
    train_s1_records = [r for r in all_s1_records if r["entity_id"] in train_ids]
    val_s1_records = [r for r in all_s1_records if r["entity_id"] in val_ids]
    print(f"Loaded {len(train_s1_records)} train S1 and {len(val_s1_records)} val S1 records in {time.time()-t0:.2f}s")

    target_true_cids = set()
    for sid in train_ids | val_ids:
        target_true_cids |= train_gt.get(sid, set())
        target_true_cids |= val_gt.get(sid, set())

    t0 = time.time()
    candidates_dict = {}
    for p in [TRAIN_SOURCE2_PATH, TRAIN_SOURCE3_PATH]:
        with open(p, "r", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)
            header = next(reader)
            for idx, row in enumerate(reader):
                if not row:
                    continue
                cid = row[1].strip() if len(row) > 1 and row[1].startswith(("S2-", "S3-")) else row[0].strip()
                if cid in target_true_cids or idx < 200000:
                    candidates_dict[cid] = {
                        "entity_id": cid,
                        "business_name": row[2].strip() if len(row) > 2 else "",
                        "business_address": row[3].strip() if len(row) > 3 else "",
                        "country": row[4].strip() if len(row) > 4 else "",
                    }
    print(f"Loaded {len(candidates_dict)} candidate pool records in {time.time()-t0:.2f}s")

    engine = BlockingEngine(max_candidates=25)
    print("Indexing candidate pool...")
    engine.index_candidates(list(candidates_dict.values()))

    print("Generating candidate pairs for training set...")
    train_blocking = {}
    for r in train_s1_records:
        train_blocking[r["entity_id"]] = engine.retrieve_candidates_for_s1(r)

    print("Generating candidate pairs for validation set...")
    val_blocking = {}
    for r in val_s1_records:
        val_blocking[r["entity_id"]] = engine.retrieve_candidates_for_s1(r)

    print("Extracting features for training pairs...")
    X_train, y_train, train_meta = build_pair_dataset(
        train_s1_records, candidates_dict, train_blocking, train_gt, max_neg_ratio=5
    )
    print(f"Train dataset: {X_train.shape[0]} pairs (Positives: {np.sum(y_train)}, Negatives: {np.sum(y_train==0)})")

    print("Extracting features for validation pairs...")
    X_val, y_val, val_meta = build_pair_dataset(
        val_s1_records, candidates_dict, val_blocking, val_gt, max_neg_ratio=None
    )
    print(f"Val dataset:   {X_val.shape[0]} pairs (Positives: {np.sum(y_val)}, Negatives: {np.sum(y_val==0)})")

    print("Training LightGBM model...")
    dtrain = lgb.Dataset(X_train, label=y_train, feature_name=FEATURE_NAMES)
    dval = lgb.Dataset(X_val, label=y_val, feature_name=FEATURE_NAMES, reference=dtrain)

    model = lgb.train(
        LGBM_PARAMS,
        dtrain,
        valid_sets=[dtrain, dval],
        callbacks=[lgb.log_evaluation(period=50)],
    )

    print("\n--- Top 10 Most Important Features ---")
    importances = model.feature_importance(importance_type="gain")
    sorted_idx = np.argsort(importances)[::-1]
    for idx in sorted_idx[:10]:
        print(f"  {FEATURE_NAMES[idx]:<25}: {importances[idx]:.1f}")

    model_path = os.path.join(MODELS_DIR, "screener_lgbm.pkl")
    with open(model_path, "wb") as f:
        pickle.dump(model, f)
    print(f"\nModel saved to {model_path}")

    print("\n" + "=" * 50)
    print("      SWEEPING DECISION THRESHOLDS FOR MACRO F_0.5")
    print("=" * 50)
    val_probs = model.predict(X_val)

    best_thresh = 0.50
    best_f05 = 0.0

    for thresh in np.arange(0.40, 0.95, 0.05):
        pred_map = {r["entity_id"]: set() for r in val_s1_records}
        for i, p in enumerate(val_probs):
            if p >= thresh:
                s1_id = val_meta[i]["s1_id"]
                cid = val_meta[i]["cand_id"]
                pred_map[s1_id].add(cid)

        eval_truth = {r["entity_id"]: val_gt.get(r["entity_id"], set()) for r in val_s1_records}
        macro_f05, stats = evaluate_predictions(eval_truth, pred_map)
        print(f"Threshold: {thresh:.2f} | Macro F_0.5: {macro_f05:.4f} | Singleton Acc: {stats['singleton_accuracy']:.2%} | Non-Singleton F0.5: {stats['non_singleton_f05']:.4f}")

        if macro_f05 > best_f05:
            best_f05 = macro_f05
            best_thresh = thresh

    print("=" * 50)
    print(f"BEST THRESHOLD: {best_thresh:.2f} => MACRO F_0.5: {best_f05:.4f}")
    print("=" * 50)

    print("\nMining active hard negatives from training candidate pairs...")
    train_probs = model.predict(X_train)
    hard_negatives = []
    s1_dict = {r["entity_id"]: r for r in train_s1_records}

    for i, p in enumerate(train_probs):
        if y_train[i] == 0 and p >= 0.35:
            s1_id = train_meta[i]["s1_id"]
            cid = train_meta[i]["cand_id"]
            if s1_id in s1_dict and cid in candidates_dict:
                s1 = s1_dict[s1_id]
                cand = candidates_dict[cid]
                hard_negatives.append({
                    "s1_id": s1_id,
                    "s1_name": s1["business_name"],
                    "s1_addr": s1["business_address"],
                    "s1_country": s1["country"],
                    "cand_id": cid,
                    "cand_name": cand["business_name"],
                    "cand_addr": cand["business_address"],
                    "cand_country": cand["country"],
                    "lgbm_score": round(float(p), 4),
                    "label": "DIFFERENT",
                })

    hard_neg_path = os.path.join(SPLIT_DIR, "active_hard_negatives.csv")
    with open(hard_neg_path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "s1_id", "s1_name", "s1_addr", "s1_country",
            "cand_id", "cand_name", "cand_addr", "cand_country",
            "lgbm_score", "label"
        ])
        writer.writeheader()
        writer.writerows(hard_negatives)

    print(f"Mined {len(hard_negatives)} hard negatives saved to: {hard_neg_path}")
    print("Stage 2 completed successfully!")


if __name__ == "__main__":
    train_screener()
